services:
  # 1. PHP App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      - DB_HOST=db 
      - DB_DATABASE=laravel_db
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
    networks:
      - laravel-net
      - private-net
    depends_on:
      - db

  # 2. Nginx Web Server
# 2. Nginx Web Server
  web:
    build:
      context: .               
      dockerfile: docker/nginx/Dockerfile 
    container_name: laravel-web
    restart: unless-stopped
    ports:
      - "8000:80"
    networks:
      - laravel-net
    depends_on:
      - app

  # 3. Database MySQL (Chuẩn Production hơn SQLite)
  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - private-net
    ports:
      - "3307" # Để bạn kết nối tool quản lý DB từ ngoài

networks:
  laravel-net:
    driver: bridge
  private-net:
    driver: bridge

volumes:
  dbdata: